# Generated by Django 4.0.6 on 2022-08-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('user_pass', models.CharField(max_length=100)),
                ('user_content', models.TextField(blank=True)),
            ],
        ),
    ]
